/* Server and client socket.io event constants*/
module.exports = {
	CLIENT_EVENTS: {
		MOVE: 'CLIENT_MOVE',
		JOIN: 'CLIENT_JOIN',
		UPDATE: 'CLIENT_UPDATE'
	},
	SERVER_EVENTS: {
		USER_JOIN: 'SERVER_USER_JOIN',
		USER_LEFT: 'SERVER_PLAYER_LEFT',
		USER_MOVED: 'SERVER_USER_MOVED',
		ROOM_STATUS: 'SERVER_ROOM_STATUS',
		UPDATE: 'SERVER_UPDATE',
		START_GAME: 'SERVER_START_GAME'
	}
}; 