

export const CONFIG = {
	WIDTH: 800,
	HEIGHT: 640,
	TILE_SIZE: 32,
	FRAME_SIZE: 32,
	PACMAN_SPEED: 200,
	WIDTH_TILES: 25,
	HEIGHT_TILES: 20,
	UPDATE_RATE: 32
};

export const SCENES = {
	BOOT: 'BOOT_SCENE',
	GAME: 'GAME_SCENE',
	MULTIPLAYER: 'MULTIPLAYER_SCENE',
	WAITING_FOR_PLAYERS: 'WAITING_FOR_PLAYERS_SCENE'
};
export const SPRITES = {
	PACMAN: 'PACMAN_SPRITE',
	GHOST: 'GHOST_SPRITE'
};
export const TILESETS = {
	POKEMON: 'POKEMON_TILESET'
};
export const TILEMAPS = {
	LEVEL: 'LEVEL_TILEMAP'
};
export const ANIMATIONS = {
	PACMAN: 'PACMAN_ANIMATION',
	GHOST: 'GHOST_LEFT_ANIMATION',
};
export const DIRECTIONS = {
	LEFT: 0,
	UP: 90,
	RIGHT: -180,
	DOWN: -90
};